#This is the vpc yaml file
AWSTemplateFormatVersion: '2010-09-09'
Description: Create a VPC with public and private subnets in each AZ

Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true

  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'

  AttachGateway:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.0.1.0/24'
      MapPublicIpOnLaunch: true

  # Add more PublicSubnet resources for each AZ

  PrivateSubnet1:
    Type: 'AWS::EC2::Subnet'
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: 'us-east-1a'
      CidrBlock: '10.0.2.0/24'

  # Add more PrivateSubnet resources for each AZ

  # Create Route Tables, Security Groups, and other necessary resources

Outputs:
  VPCId:
    Description: 'VPC Id'
    Value: !Ref VPC
